# Generated by Django 3.2.6 on 2021-08-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfReturn', models.DateTimeField(auto_now=True)),
                ('returnBuy', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnTovar', to='myapp.buy')),
            ],
        ),
    ]
