# Generated by Django 3.2.6 on 2021-08-14 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_returnbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbuy',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='USERRRR', to=settings.AUTH_USER_MODEL),
        ),
    ]
