# Generated by Django 3.2.6 on 2021-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_returnbuy_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='canReturn',
            field=models.BooleanField(default=True),
        ),
    ]
