# Generated by Django 3.2.6 on 2021-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_buy_canreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='timeOfBuy',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
