# Generated by Django 3.2.6 on 2021-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_buy_timeofbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='timeOfBuy',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
